import type { ThemeConfig, OSTheme } from '@/types/theme';

export const THEMES_CONFIG: Record<OSTheme, ThemeConfig> = {
  macos: {
    id: 'macos',
    name: 'macOS 26',
    description: 'macOS with Liquid Glass — dock at bottom, menubar at top',
    hasLiquidGlass: true,
    hasFloatingWindows: true,
    hasDock: true,
    hasMenuBar: true,
    hasTaskbar: false,
    hasNavBar: false,
    defaultWallpaper: 'macos-default',
    layout: {
      desktopInsets: { top: 36, right: 0, bottom: 60, left: 0 },
      chrome: {
        menuBarHeight: 28,
        dockHeight: 72,
        dockOffsetBottom: 8,
        taskbarHeight: 0,
        navBarHeight: 0,
        statusBarHeight: 0,
        windowChromeHeight: 44,
      },
      window: {
        maximizeInsets: { top: 28, bottom: 0 },
        dragTopInset: 28,
        minTitleVisibleHeight: 40,
      },
    },
  },
  ipad: {
    id: 'ipad',
    name: 'iPad OS 26',
    description: 'iPad OS with Liquid Glass — home screen grid with dock',
    hasLiquidGlass: true,
    hasFloatingWindows: true,
    hasDock: true,
    hasMenuBar: false,
    hasTaskbar: false,
    hasNavBar: false,
    defaultWallpaper: 'macos-default',
    layout: {
      desktopInsets: { top: 36, right: 0, bottom: 64, left: 0 },
      chrome: {
        menuBarHeight: 28,
        dockHeight: 80,
        dockOffsetBottom: 8,
        taskbarHeight: 0,
        navBarHeight: 0,
        statusBarHeight: 28,
        windowChromeHeight: 44,
      },
      window: {
        maximizeInsets: { top: 28, bottom: 96 },
        dragTopInset: 28,
        minTitleVisibleHeight: 40,
      },
    },
  },
  iphone: {
    id: 'iphone',
    name: 'iPhone OS 26',
    description: 'iPhone OS with Liquid Glass — fullscreen apps, bottom nav',
    hasLiquidGlass: true,
    hasFloatingWindows: false,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: false,
    hasNavBar: true,
    defaultWallpaper: 'macos-default',
    layout: {
      desktopInsets: { top: 40, right: 0, bottom: 80, left: 0 },
      chrome: {
        menuBarHeight: 0,
        dockHeight: 0,
        dockOffsetBottom: 0,
        taskbarHeight: 0,
        navBarHeight: 56,
        statusBarHeight: 40,
        windowChromeHeight: 0,
      },
      window: {
        maximizeInsets: { top: 0, bottom: 0 },
        dragTopInset: 0,
        minTitleVisibleHeight: 40,
      },
    },
  },
  windows: {
    id: 'windows',
    name: 'Windows 11',
    description: 'Windows 11 — centered taskbar at bottom, floating windows',
    hasLiquidGlass: false,
    hasFloatingWindows: true,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: true,
    hasNavBar: false,
    defaultWallpaper: 'windows-default',
    layout: {
      desktopInsets: { top: 0, right: 0, bottom: 48, left: 0 },
      chrome: {
        menuBarHeight: 0,
        dockHeight: 0,
        dockOffsetBottom: 0,
        taskbarHeight: 48,
        navBarHeight: 0,
        statusBarHeight: 0,
        windowChromeHeight: 36,
      },
      window: {
        maximizeInsets: { top: 0, bottom: 48 },
        dragTopInset: 0,
        minTitleVisibleHeight: 40,
      },
    },
  },
  android: {
    id: 'android',
    name: 'Android',
    description: 'Android — material design, bottom nav bar',
    hasLiquidGlass: false,
    hasFloatingWindows: false,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: false,
    hasNavBar: true,
    defaultWallpaper: 'android-default',
    layout: {
      desktopInsets: { top: 32, right: 0, bottom: 56, left: 0 },
      chrome: {
        menuBarHeight: 0,
        dockHeight: 0,
        dockOffsetBottom: 0,
        taskbarHeight: 0,
        navBarHeight: 56,
        statusBarHeight: 32,
        windowChromeHeight: 0,
      },
      window: {
        maximizeInsets: { top: 0, bottom: 0 },
        dragTopInset: 0,
        minTitleVisibleHeight: 40,
      },
    },
  },
};
