import type { ThemeConfig, OSTheme } from '@/types/theme';

export const THEMES_CONFIG: Record<OSTheme, ThemeConfig> = {
  macos: {
    id: 'macos',
    name: 'macOS 26',
    description: 'macOS with Liquid Glass — dock at bottom, menubar at top',
    hasLiquidGlass: true,
    hasFloatingWindows: true,
    hasDock: true,
    hasMenuBar: true,
    hasTaskbar: false,
    hasNavBar: false,
    defaultWallpaper: 'macos-default',
  },
  ipad: {
    id: 'ipad',
    name: 'iPad OS 26',
    description: 'iPad OS with Liquid Glass — home screen grid with dock',
    hasLiquidGlass: true,
    hasFloatingWindows: true,
    hasDock: true,
    hasMenuBar: true,
    hasTaskbar: false,
    hasNavBar: false,
    defaultWallpaper: 'macos-default',
  },
  iphone: {
    id: 'iphone',
    name: 'iPhone OS 26',
    description: 'iPhone OS with Liquid Glass — fullscreen apps, bottom nav',
    hasLiquidGlass: true,
    hasFloatingWindows: false,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: false,
    hasNavBar: true,
    defaultWallpaper: 'macos-default',
  },
  windows: {
    id: 'windows',
    name: 'Windows 11',
    description: 'Windows 11 — centered taskbar at bottom, floating windows',
    hasLiquidGlass: false,
    hasFloatingWindows: true,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: true,
    hasNavBar: false,
    defaultWallpaper: 'windows-default',
  },
  android: {
    id: 'android',
    name: 'Android',
    description: 'Android — material design, bottom nav bar',
    hasLiquidGlass: false,
    hasFloatingWindows: false,
    hasDock: false,
    hasMenuBar: false,
    hasTaskbar: false,
    hasNavBar: true,
    defaultWallpaper: 'android-default',
  },
};
